# Generated by Django 6.0.3 on 2026-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profileimage_file_profileimage_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
