# Generated by Django 6.0.3 on 2026-05-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_vote_unique_together_vote_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentVote',
        ),
    ]
